create table if not exists public.pins (
  id bigint generated by default as identity primary key,
  name text,
  city text not null,
  country text not null,
  emoji text default '📍',
  latitude double precision not null,
  longitude double precision not null,
  created_at timestamptz default now()
);

alter table public.pins enable row level security;

drop policy if exists "Anyone can view pins" on public.pins;
create policy "Anyone can view pins" on public.pins
  for select to anon using (true);

drop policy if exists "Anyone can add pins" on public.pins;
create policy "Anyone can add pins" on public.pins
  for insert to anon with check (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_rel
    where pubname = 'supabase_realtime'
      and pubrelid = 'public.pins'::regclass
  ) then
    alter publication supabase_realtime add table public.pins;
  end if;
end $$;
