import { useEffect, useMemo, useRef, useState } from 'react'
import { Check, ChevronDown, Crosshair, Globe2, MapPin, Minus, Plus, Search, Sparkles, X } from 'lucide-react'
import { cities, type City } from './data/cities'
import type { Marker } from './types'

const seedMarkers: Marker[] = [
  { ...cities.find(c=>c.id==='auckland-nz')!, id:'seed-auckland', createdAt:new Date().toISOString() },
  { ...cities.find(c=>c.id==='london-gb')!, id:'seed-london', createdAt:new Date().toISOString() },
  { ...cities.find(c=>c.id==='tokyo-jp')!, id:'seed-tokyo', createdAt:new Date().toISOString() },
]
function project(lat:number,lng:number,offset=0){return {left:`${(lng+180)/360*100+Math.sin(offset*4.7)*.45}%`,top:`${(90-lat)/180*100+Math.cos(offset*3.1)*.35}%`}}

export default function App(){
  const [markers,setMarkers]=useState<Marker[]>([]),[query,setQuery]=useState(''),[selected,setSelected]=useState<City|null>(null),[zoom,setZoom]=useState(1),[mapOffset,setMapOffset]=useState({x:0,y:0}),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(false),[submitting,setSubmitting]=useState(false),[status,setStatus]=useState<'idle'|'success'|'error'>('idle'),[panelOpen,setPanelOpen]=useState(false)
  const dragRef=useRef({active:false,x:0,y:0,startX:0,startY:0})
  useEffect(()=>{fetch('/api/markers').then(async r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setMarkers(d.markers??[])).catch(()=>{if(import.meta.env.DEV)setMarkers(seedMarkers);else setLoadError(true)}).finally(()=>setLoading(false))},[])
  const suggestions=useMemo(()=>{const text=query.trim().toLocaleLowerCase();return text?cities.filter(c=>`${c.name} ${c.country}`.toLocaleLowerCase().includes(text)).slice(0,6):[]},[query])
  async function submit(){if(!selected||submitting)return;setSubmitting(true);setStatus('idle');const optimistic={...selected,id:crypto.randomUUID(),createdAt:new Date().toISOString()};try{const r=await fetch('/api/markers',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(selected)});if(!r.ok)throw Error();const d=await r.json();setMarkers(m=>[...m,d.marker??optimistic]);setStatus('success');setSelected(null);setQuery('')}catch{setStatus('error')}setSubmitting(false);window.setTimeout(()=>setStatus('idle'),4200)}
  function choose(city:City){setSelected(city);setQuery(city.name);setPanelOpen(false);setZoom(z=>Math.max(1.2,z))}
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"><Globe2 size={20}/></span><span>WHERE ARE WE?</span></div><div className="topbar-note"><span className="live-dot"/> 全球实时汇聚</div></header>
    <section className="intro"><div><p className="eyebrow"><Sparkles size={14}/> A MAP OF US</p><h1>你从哪里来？</h1><p className="intro-copy">在地图上留下你的城市，看看世界各地的我们如何相遇。</p></div><div className="stats"><div><strong>{markers.length.toLocaleString()}</strong><span>已留下足迹</span></div><div><strong>{new Set(markers.map(m=>m.country)).size}</strong><span>个国家 / 地区</span></div></div></section>
    <section className="workspace"><div className="map-card"><div className="map-toolbar"><span><span className="legend-dot"/> 每一个光点，都是一个人</span><div className="zoom-controls"><button aria-label="缩小地图" onClick={()=>setZoom(z=>Math.max(1,z-.2))}><Minus size={16}/></button><button aria-label="放大地图" onClick={()=>setZoom(z=>Math.min(2.4,z+.2))}><Plus size={16}/></button><button aria-label="重置地图" onClick={()=>{setZoom(1);setMapOffset({x:0,y:0})}}><Crosshair size={16}/></button></div></div><div className="map-viewport" onPointerDown={e=>{dragRef.current={active:true,x:e.clientX,y:e.clientY,startX:mapOffset.x,startY:mapOffset.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(dragRef.current.active)setMapOffset({x:dragRef.current.startX+e.clientX-dragRef.current.x,y:dragRef.current.startY+e.clientY-dragRef.current.y})}} onPointerUp={()=>{dragRef.current.active=false}} onPointerCancel={()=>{dragRef.current.active=false}} onWheel={e=>setZoom(z=>Math.min(2.4,Math.max(1,z+(e.deltaY<0?.12:-.12))))}><svg className="world-map" viewBox="0 0 1000 500" role="img" aria-label="世界地图"><defs><pattern id="grid" width="50" height="50" patternUnits="userSpaceOnUse"><path d="M 50 0 L 0 0 0 50" fill="none" stroke="#31516b" strokeWidth=".7" opacity=".22"/></pattern></defs><rect width="1000" height="500" fill="url(#grid)"/><g className="continents"><path d="M99 122l44-30 83 13 54 37-13 35-51 5-22 37-41-18-28-36zM248 201l59 8 41 53-10 74-43 49-26-35 9-53-34-40zM461 116l49-22 70 14 38 39-15 32-66-2-24 40-36-24-28-46zM548 215l74-12 79 33 6 41-48 13-36 57-35 2-22-62-35-24zM701 111l86 3 65 34-13 31-48 3-18 50-40-30-47-17zM786 281l82-7 67 48-13 48-75 9-46-38zM171 421l53-13 55 22-24 34-60 6z"/></g></svg><div className="marker-layer" style={{transform:`translate(${mapOffset.x}px,${mapOffset.y}px) scale(${zoom})`}}>{markers.map((m,i)=><span key={m.id} className="marker" style={project(m.lat,m.lng,i)} title={`${m.name} · ${m.country}`}><i/></span>)}{selected&&<span className="marker selected-marker" style={project(selected.lat,selected.lng,markers.length)}><i/></span>}</div>{loading&&<div className="map-message">正在连接世界…</div>}{!loading&&loadError&&<div className="map-message empty-map"><MapPin size={20}/><span>暂时无法连接地图数据<br/><small>请稍后刷新重试</small></span></div>}{!loading&&!loadError&&!markers.length&&<div className="map-message empty-map"><MapPin size={20}/><span>地图还是空的<br/><small>成为第一个留下足迹的人</small></span></div>}</div><div className="map-footer"><span>拖动地图探索 · 滚轮缩放</span><span>数据仅保留城市和国家</span></div></div>
      <aside className="action-card"><div className="card-heading"><span className="step-badge">01</span><div><h2>标记你的城市</h2><p>你现在在哪里？</p></div></div><div className="search-wrap"><Search size={18}/><input value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);setPanelOpen(true)}} onFocus={()=>setPanelOpen(true)} placeholder="搜索城市…" aria-label="搜索城市"/>{query&&<button className="clear-button" onClick={()=>{setQuery('');setSelected(null)}} aria-label="清除搜索"><X size={16}/></button>}{panelOpen&&query&&<div className="suggestions">{suggestions.length?suggestions.map(c=><button key={c.id} onClick={()=>choose(c)}><MapPin size={16}/><span><b>{c.name}</b><small>{c.country}</small></span><ChevronDown size={15} className="suggestion-arrow"/></button>):<div className="no-results">没有找到这个城市，试试其他拼写</div>}</div>}</div>{selected?<div className="selected-city"><div className="selected-icon"><MapPin size={19}/></div><div><strong>{selected.name}</strong><span>{selected.country}</span></div><Check size={18} className="selected-check"/></div>:<div className="helper-text">搜索并选择一个城市<br/>它会在地图上亮起</div>}<button className="submit-button" disabled={!selected||submitting} onClick={submit}>{submitting?'正在留下足迹…':'确认标记'}<span>→</span></button>{status==='success'&&<div className="toast success"><Check size={16}/> 你的城市已经出现在地图上</div>}{status==='error'&&<div className="toast error">提交失败，请稍后重试</div>}<p className="privacy-note">我们只保存城市和国家，不保存姓名、邮箱或精确位置。</p><button className="browse-button" onClick={()=>setPanelOpen(false)}>先看看大家在哪里 <span>↓</span></button></aside></section>
    <footer className="footer"><span>一个属于所有人的地图</span><span>{new Set(markers.map(m=>m.name)).size} 个城市正在发光</span></footer>
  </main>
}
